import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/features/Header/Header";
import Footer from "@/features/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body
          style={{margin: "0 auto !important", padding: "0 !important", overflow: "auto !important"}}
      >
      <Header/>
      <div className={"flex flex-col max-w-[1280px] w-full"}>
        {children}
      </div>
      <Footer/>
      </body>
      </html>
  );
}
